### ISSUE TITLE
Received status code 502 from server: Bad Gateway!! Was Working fine till yesterday.

### ISSUE THREAD

**Issue by tazsid** [transistorsoft/flutter_background_fetch#256]
* Plugin version: 1.0.3
* Platform: Android
* OS version: 10
* Device manufacturer / model: Redmi 9A
* Flutter info (`Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision 3595343e20 (9 weeks ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3, `Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)  
[√] Android Studio (version 2020.3)
[√] Connected device (2 available)

• No issues found!`):

**Could not GET 'https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'. Received status code 502 from server: Bad Gateway**

**Comment by Tek56** [comment]
Same here:

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :background_fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'. Received status code 502 from server: Bad Gateway`

**Comment by christocracy** [comment]
Post your android/build.gradle

**Comment by Tek56** [comment]
`buildscript {
    ext.kotlin_version = '1.5.10' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion   = 30                // or higher
        targetSdkVersion    = 30                // or higher
        appCompatVersion    = "1.0.2"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
    }

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by christocracy** [comment]
Please learn to [syntax highlight code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by Tek56** [comment]
Done, sorry @christocracy

**Comment by christocracy** [comment]
Do you know that [the `jcenter()` repository is deprecated](https://blog.gradle.org/jcenter-shutdown#:~:text=On%20February%203%202021%2C%20JFrog,disruptions%20to%20your%20build%20pipelines.)?

Look at the `repositories` section of a freshly generated flutter app:

```gradle
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by christocracy** [comment]
Look at the [`android/build.gradle` of the /example app](https://github.com/transistorsoft/flutter_background_fetch/blob/master/example/android/build.gradle) here in this repo.

**Comment by Tek56** [comment]
Yep thanks for that, I took the example of the build gradle.
I still have the issue 
````
Could not GET 'https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
````

**Comment by nhoangthinh** [comment]
i got the same on this issue

**Comment by nhoangthinh** [comment]
<img width="1328" alt="Screen Shot 2021-11-30 at 22 20 47" src="https://user-images.githubusercontent.com/35698467/144075230-fe3f2cad-5364-4334-8f04-3408548d3ef1.png">

background_fetch: 1.0.3

**Comment by nhoangthinh** [comment]
buildscript {
    ext.kotlin_version = '1.4.0' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion   = 30                // or higher
        targetSdkVersion    = 30                // or higher
        appCompatVersion    = "1.2.0"           // or higher
   }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.3'
        classpath 'com.google.gms:google-services:4.3.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by Tek56** [comment]
This is my updated android/build.gradle
````
buildscript {
    ext.kotlin_version = '1.5.31'
    ext {
        compileSdkVersion   = 30
        targetSdkVersion    = 30
        supportLibVersion   = "1.3.1"
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
````

**Comment by christocracy** [comment]
I just generated a fresh flutter app `$ flutter create foo`.  Followed the installation steps here in this repo and the app boots without issue.

**Comment by christocracy** [comment]
@nhoangthinh [See my comment above](https://github.com/transistorsoft/flutter_background_fetch/issues/256#issuecomment-982667487).  I'm not looking at your posted code until you *Syntax Highlight* it.

**Comment by nhoangthinh** [comment]
```
buildscript {
    ext.kotlin_version = '1.5.31' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion   = 30                // or higher
        targetSdkVersion    = 30                // or higher
        appCompatVersion    = "1.3.1"           // or higher
   }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.3'
        classpath 'com.google.gms:google-services:4.3.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by nhoangthinh** [comment]
> @nhoangthinh [See my comment above](https://github.com/transistorsoft/flutter_background_fetch/issues/256#issuecomment-982667487). I'm not looking at your posted code until you _Syntax Highlight_ it.
sorry @christocracy , i updated my code

**Comment by christocracy** [comment]
and `$ flutter upgrade`

**Comment by Tek56** [comment]
Still the same bug. Like you said, my app is attempting to find `maven-metadata.xml` from `google.bintray.com`. instead of searching for the one within the plugin.

I tried:

- Updating Flutter (`$ flutter ugprade`)
- Cleaning my build (`$ ./gradlew clean`)

About my app/versions:

- My app is updated [post-1.12](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)
- Flutter 2.6.0-12.0.pre.854
- Dart 2.16.0 (build 2.16.0-55.0.dev) • DevTools 2.8.0
- Gradle 6.3

**Comment by christocracy** [comment]
I suggest you generate yourself a fresh flutter app, follow the setup instructions and verify the plugin builds fine.

**Comment by sohubill** [comment]
I got the same problem from yesterday

**Comment by christocracy** [comment]
Create for me a freshly generated flutter app which reproduces this then share that repo with me.

**Comment by tazsid** [comment]
I don't know how but it is working again today. Haven't done any specific changes. Anyways thank you. :)

**Comment by DiepEsc** [comment]
There changes in ```android/build.gradle``` seen to work for me.

```diff
 buildscript {
     ext.kotlin_version = '1.4.0' // Must use 1.3.0 or higher.
     ext {
         compileSdkVersion   = 30                // or higher
         targetSdkVersion    = 30                // or higher
         appCompatVersion    = "1.2.0"           // or higher
    }
 
     repositories {
         google()
-        jcenter()
+        mavenCentral()
     }
 
     dependencies {
-        classpath 'com.android.tools.build:gradle:4.0.1'
+        classpath 'com.android.tools.build:gradle:4.2.2'
         classpath 'com.google.gms:google-services:4.3.2'
         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.1'
     }
 }
 
 allprojects {
     repositories {
         google()
-        jcenter()
         maven {
             // [required] background_fetch
             url "${project(':background_fetch').projectDir}/libs"
         }
+        mavenCentral {
+            content {
+                excludeGroupByRegex "com\\.google\\.android\\.gms"
+            }
+        }
 
     }
 }
```

**Comment by asmodeoux** [comment]
The issue is back today, Maven is seeing this mention in build.gradle:
`implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '+')`

and tries to get it from Bintray repository, but since [bintray repository is sunset since this December](https://status.bintray.com) it fails to get it. It's a good question why is it trying to get it from a remote repo and not local file inside plugin, but we have to force it using the local one somehow.

**Comment by asmodeoux** [comment]
Replacing the `+` version with an actual version name fixed the problem for me

`implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '+')` —> `implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '0.5.0')`

Also, the order of repositories matters, make sure you put
```
        maven {
            url './libs'
        }
```
above google() and mavenCentral()

**Comment by G-Luz** [comment]
My problem it's same: 

> Running Gradle task 'assembleDebug'...
[flutter_background_geolocation] Purging debug resources in release build

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :background_fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Finished with error: Gradle task assembleDebug failed with exit code 1

How solve this problem?

**Comment by Tek56** [comment]
> The issue is back today, Maven is seeing this mention in build.gradle: `implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '+')`

Hi,
`I don't have the line inside my build.gradle, could you show us where to add the following line please : 
implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '0.5.0')`

**Comment by Tek56** [comment]
Thanks a lot @asmodeoux.
@G-Luz,
in app/build.gradle, add the following line:
`implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '0.5.0')`
in build.gradle, add the following lines BEFORE google() and mavenCentral():
`
        maven {
            url './libs'
        }
`

**Comment by G-Luz** [comment]
> Thanks a lot @asmodeoux. @G-Luz, in app/build.gradle, add the following line: `implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '0.5.0')` in build.gradle, add the following lines BEFORE google() and mavenCentral(): `maven { url './libs' }`

Thank you for reply. I continue received error, but it's a new error: 

![Captura de tela de 2021-12-08 20-01-17](https://user-images.githubusercontent.com/58195699/145305415-4d35e9ef-6bf7-44a9-9538-817ff57ce288.png)

My app/build.gradle:

```
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '0.5.0')
}

apply plugin: 'com.google.gms.google-services'
```

My android/build.gradle:

```
buildscript {

    ext.kotlin_version = '1.3.0' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion = 29                // or higher
        targetSdkVersion = 29                // or higher
        appCompatVersion = "1.0.2"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
    }

    repositories {
        maven { url './libs' }
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.3.2'
    }
}

allprojects {
    repositories {
        maven { url './libs' }
        google()
        jcenter()
    }
}
```

**Comment by christocracy** [comment]
@G-Luz Look at the [`build.gradle` from a freshly generated Flutter app that I posted above](https://github.com/transistorsoft/flutter_background_fetch/issues/256#issuecomment-982701302).  Notice there is *no* `jcenter`.

You should **not** see `jcenter` *at all*.  [jcenter is DEAD](https://blog.gradle.org/jcenter-shutdown#:~:text=On%20February%203%202021%2C%20JFrog,disruptions%20to%20your%20build%20pipelines.)

**Comment by G-Luz** [comment]
Yes jcenter is DEAD, sorry. I send my build.gradle before make new changes (change to mavenCentral).

My output after change to mavenCentral():

![Captura de tela de 2021-12-08 21-23-05](https://user-images.githubusercontent.com/58195699/145312187-81e548d4-25de-4156-90ce-c9bea51e9a63.png)

My android/build.gradle:

```
buildscript {

    ext.kotlin_version = '1.3.0' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion = 29                // or higher
        targetSdkVersion = 29                // or higher
        appCompatVersion = "1.0.2"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
    }

    repositories {
        maven { url './libs' }
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.3.2'
    }
}

allprojects {
    repositories {
        maven { url './libs' }
        google()
        mavenCentral()
    }
}
```

**Comment by asmodeoux** [comment]
@G-Luz @Tek56 you guys got me wrong, the error is in the background_fetch plugin's build gradle. You should fork it and change it's android/build.gradle to use some exact version instead of a + sign, or wait for devs to fix it.

**Comment by FatiMooni** [comment]
> There changes in `android/build.gradle` seen to work for me.
> 
> ```diff
>  buildscript {
>      ext.kotlin_version = '1.4.0' // Must use 1.3.0 or higher.
>      ext {
>          compileSdkVersion   = 30                // or higher
>          targetSdkVersion    = 30                // or higher
>          appCompatVersion    = "1.2.0"           // or higher
>     }
>  
>      repositories {
>          google()
> -        jcenter()
> +        mavenCentral()
>      }
>  
>      dependencies {
> -        classpath 'com.android.tools.build:gradle:4.0.1'
> +        classpath 'com.android.tools.build:gradle:4.2.2'
>          classpath 'com.google.gms:google-services:4.3.2'
>          classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.1'
>      }
>  }
>  
>  allprojects {
>      repositories {
>          google()
> -        jcenter()
>          maven {
>              // [required] background_fetch
>              url "${project(':background_fetch').projectDir}/libs"
>          }
> +        mavenCentral {
> +            content {
> +                excludeGroupByRegex "com\\.google\\.android\\.gms"
> +            }
> +        }
>  
>      }
>  }
> ```

This worked for me , I upgraded gradle version to `4.2.2` in addition to following the instructions of Android Setup for `background_fetch` [THIS ONE](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md)

**Comment by G-Luz** [comment]
Hi, @asmodeoux!
I understand you solution to problem and I change my android/build.gradle background_fetch plugin, but not working for me. 

My console output:
![Captura de tela de 2021-12-09 13-04-40](https://user-images.githubusercontent.com/58195699/145432414-a263bbe6-98ea-474a-a8e0-525d7a284016.png)

My backgroud_fetch plugin **android/build.gradle**:

```
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
    }
}

rootProject.allprojects {
    repositories {
        maven {
            url './libs'
        }
        google()
        mavenCentral()
        
    }
}

apply plugin: 'com.android.library'

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 28)

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '0.5.0')
    implementation "androidx.appcompat:appcompat:${safeExtGet('appCompatVersion', "1.1.0")}"
}

``` 
My steps for tries implements this solution:

I search my **background_fetch plugin folder** > open android folder and build.gradle file > I make changes that your related in your post (put maven { url './libs'} before google() and mavenCentral() and change ```implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '+')``` to  ```implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '0.5.0')```

Not work to me :(

You have another solution to fixed problem?

**Comment by asmodeoux** [comment]
@G-Luz it seems to me you're editing your pub cache files, it's not a good way of handling this issue. It will get reset after some time. You need to actually fork this repository, change this line and then add your fork to your pubspec.yaml instead of the original library.

**Comment by kisszyj** [comment]
![image](https://user-images.githubusercontent.com/33854839/145520000-08751aa4-87e0-4ee2-928c-de938c844f85.png)

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by G-Luz** [comment]
Hi, @asmodeoux! 
I follow your steps for solution, but not work for me. 

My steps: 
I fork the **flutter_background_geolocation** and **background_fetch** plugins ➝ make a reference in my pubspec.yaml project for using my **flutter_background_geolocation** local plugin and includes my fork from **background_fetch** to **flutter_background_geolocation** pubspec.yaml ➝ and make changes that you gave in **background_fetch/android/build.gradle**

**My project pubspec.yaml:**
```
dependencies:
    flutter:
      sdk: flutter
  {...}
  flutter_background_geolocation:
    path: './flutter_background_geolocation_1_10_1'
```

**Local plugin in file explorer: flutter_background_geolocation and background_fetch**
![Captura de tela de 2021-12-10 10-31-11](https://user-images.githubusercontent.com/58195699/145581781-4fdcf652-1454-402d-93c8-d65041c4e09a.png)

**flutter_background_geolocation pubspec.yaml**

```
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
#  background_fetch: ^0.6.0       //commented line for using local plugin
  background_fetch:
    path: './flutter_background_fetch'
```

**android/build.gradle from background_fetch plugin**

```
group 'com.transistorsoft.flutter.backgroundfetch'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
    }
}

rootProject.allprojects {
    repositories {
        maven {
            url './libs'
        }
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 28)

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation(group: 'com.transistorsoft', name:'tsbackgroundfetch', version: '0.5.0')        _this line not working_
    implementation "androidx.appcompat:appcompat:${safeExtGet('appCompatVersion', "1.1.0")}"
}

```
**My console output:**
![Captura de tela de 2021-12-10 10-38-53](https://user-images.githubusercontent.com/58195699/145582738-9ecdd536-9321-453c-90a0-4b11fa5f7f0a.png)

Did I forget a step?

Can you help me, please.

**Comment by christocracy** [comment]
@G-Luz if this is your `android/build.gradle` then *yes* -- you missed a step.  Read the [Android Setup](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#androidbuildgradle)

**Comment by G-Luz** [comment]
@christocracy My project android/build.gradle is correct, because plugin already it worked in the last week. 
In my last publication I send my **background_fetch/android/build.gradle**.

**My project android/build_gradle:**

```
buildscript {

    ext.kotlin_version = '1.3.0' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion = 29                // or higher
        targetSdkVersion = 29                // or higher
        appCompatVersion = "1.0.2"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.3.2'
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
           // [required] flutter_background_geolocation
                   url "${project(':flutter_background_geolocation').projectDir}/libs"
       }
       maven {
           // [required] background_fetch
                   url "${project(':background_fetch').projectDir}/libs"
       }
    }
}
```

**My project android/app/build.gradle:**

```targetSdkVersion rootProject.ext.targetSdkVersion```

I continue receive error in console output.

You have another solution?

**Comment by christocracy** [comment]
>You have another solution?

I am unable to reproduce this problem.  Can someone please generate a fresh new flutter app that reproduces the problem.  Share it with me in a public Github repo.

**Comment by christocracy** [comment]
@G-Luz Btw, I suggest you use the [latest version](https://pub.dev/packages/flutter_background_geolocation/versions) of `flutter_background_geolocation` (`4.3.2`).

You seem to be using `1.1.0` from *2 years ago*.

**Comment by christocracy** [comment]
And if you're *manually* adding `background_fetch` as a dependency in your `pubspec.yaml` (you don't need to do that if you're using `flutter_background_geolocation`, since `background_geoloation` already defines `background_fetch` as its own dependency), `background_geolocation@4.3.2` wants [`background_fetch@1.0.3`](https://pub.dev/packages/background_fetch/versions).

**Comment by G-Luz** [comment]
Hi again, @christocracy!

My problem not solved. I created new [project](https://github.com/G-Luz/flutter-background-geolocation-test) to reproduce this error.

You tries run project to check if exists problems, please.

I make a readme in project, because to your check the project settings. 

My console output:
![Captura de tela de 2021-12-10 22-22-59](https://user-images.githubusercontent.com/58195699/145658843-a23cd6b9-20eb-438a-8316-d14f88e52862.png)

**I wait your return, thank you!**

**Comment by christocracy** [comment]
There’s no code in that repo, only a readme.

**Comment by G-Luz** [comment]
@christocracy change from main branch to master, please

**Comment by christocracy** [comment]
Why have you [commented-out background_geolocation maven url](https://github.com/G-Luz/flutter-background-geolocation-test/blob/cc63cb777947a60ab2ef38985264bbeecd009ddc/android/build.gradle#L27)?  That will obviously cause a build failure.

**Comment by christocracy** [comment]
Your error screenshot is precisely the error I would expect to see when background_geolocation has no maven url, which you commented-out.

**Comment by G-Luz** [comment]
this [link](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#:~:text=maven%20%7B%0A%2B%20%20%20%20%20%20%20%20%20%20%20//%20%5Brequired%5D%20background_fetch%0A%2B%20%20%20%20%20%20%20%20%20%20%20url%20%22%24%7Bproject(%27%3Abackground_fetch%27).projectDir%7D/libs%22%0A%2B%20%20%20%20%20%20%20%7D)  is not specified this line, but also continue generate error: 

![Captura de tela de 2021-12-10 22-44-37](https://user-images.githubusercontent.com/58195699/145659652-435a6725-f357-46b4-b035-452be14f3871.png)

Thank you for attention

**Comment by christocracy** [comment]
Your [pubspec.yaml](https://github.com/G-Luz/flutter-background-geolocation-test/blob/cc63cb777947a60ab2ef38985264bbeecd009ddc/pubspec.yaml#L33) show you are importing `flutter_background_geolocation`.

Therefore, you follow the [flutter_background_geolocation Setup](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/help/INSTALL-ANDROID.md)

![](https://dl.dropbox.com/s/bhik1s7x15jqb77/Screen%20Shot%202021-12-10%20at%208.50.20%20PM.png?dl=1)

**Comment by christocracy** [comment]
What the hell dude?  I have little faith in your ability to follow directions.

![](https://www.dropbox.com/s/r48cnvnzvhayadu/Screen%20Shot%202021-12-10%20at%209.01.22%20PM.png?dl=1)

![](https://dl.dropbox.com/s/m50ys6fwnb3bcs0/Screen%20Shot%202021-12-10%20at%209.03.14%20PM.png?dl=1)

Let me know when your project is **correctly configured**.

**Comment by christocracy** [comment]
**AND** you pasted the [`tools:replace=-"android:label"](https://github.com/G-Luz/flutter-background-geolocation-test/blob/master/android/app/src/main/AndroidManifest.xml#L8-L9) **ON THE `<activity>` element!

![](https://dl.dropbox.com/s/42bgb8n9q6e9lrw/Screen%20Shot%202021-12-10%20at%209.08.29%20PM.png?dl=1)
The *Setup Instructions* tell you to place it in the `<application>` element.

![](https://dl.dropbox.com/s/c7vzvpoys8nuih6/Screen%20Shot%202021-12-10%20at%209.08.03%20PM.png?dl=1)

**Comment by christocracy** [comment]
You need start from scratch and **CAREFULLY** follow the *Setup Instructions*.

**Comment by tazsid** [comment]
After deleting `pubspec.lock` file and upgrading `firebase_messaging` to `11.2.3` it is working now.

**Comment by poqueque** [comment]
Thanks @tazsid that fixed it in my project. For the record, I've been using this library for more than a year now and the 502 issue just appear when compiling this morning...

**Comment by christocracy** [comment]
@poqueque what version background_geolocation?  This matters

**Comment by G-Luz** [comment]
@tazsid not work for me :(

**Comment by G-Luz** [comment]
In my real project I continue received this exception:
![Captura de tela de 2021-12-13 12-03-18](https://user-images.githubusercontent.com/58195699/145836216-553627b8-000a-4255-bb2e-51eb7338170b.png)

**Comment by christocracy** [comment]
@G-Luz you need to concentrate on getting your simple [hello world](https://github.com/G-Luz/flutter-background-geolocation-test).  I got your simple project to boot.

```diff
diff --git a/android/app/src/main/AndroidManifest.xml b/android/app/src/main/AndroidManifest.xml
index bbf0419..79a3096 100644
--- a/android/app/src/main/AndroidManifest.xml
+++ b/android/app/src/main/AndroidManifest.xml
@@ -1,12 +1,12 @@
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
-    xmlns:tools="http://schemas.android.com/to ols"
+    xmlns:tools="http://schemas.android.com/tools"
     package="com.example.flutter_geolocation_test">

     <application
         android:icon="@mipmap/ic_launcher"
+        tools:replace="android:label"
         android:label="flutter_geolocation_test">
         <activity
-            tools:replace="android:label"
             android:name=".MainActivity"
             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
             android:hardwareAccelerated="true"
diff --git a/android/build.gradle b/android/build.gradle
index 40c0929..de235ff 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -1,8 +1,8 @@
 buildscript {
-    ext.kotlin_version = '1.3.50' // Must use 1.3.0 or higher.
+    ext.kotlin_version = '1.4.32' // Must use 1.3.0 or higher.
     ext {
-        compileSdkVersion = 29                // or higher
-        targetSdkVersion = 29                // or higher
+        compileSdkVersion = 31                // or higher
+        targetSdkVersion = 30                // or higher
         appCompatVersion = "1.0.2"           // or higher
         playServicesLocationVersion = "17.0.0"  // or higher
     }
@@ -22,10 +22,10 @@ allprojects {
     repositories {
         google()
         mavenCentral()
-//        maven {
-//            // [required] flutter_background_geolocation
-//            url "${project(':flutter_background_geolocation').projectDir}/libs"
-//        }
+        maven {
+            // [required] flutter_background_geolocation
+            url "${project(':flutter_background_geolocation').projectDir}/libs"
+        }
         maven {
             // [required] background_fetch
             url "${project(':background_fetch').projectDir}/libs"

```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.6.0-12.0.pre.1003, on macOS 12.0.1 21A559 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
```

**Comment by G-Luz** [comment]
Hi, @christocracy!
I made a mistake in the test project, but I fix the configuration problems and run correctly. But in my real/release project the problem continues. I check and compare the plugin implementation at two projects (test project and real project), but the implementation is the like. 
I don't know if related with another declarete plugins in pubspec.yaml.

**Comment by poqueque** [comment]
@christocracy I had 4.3.1. I updated to 4.3.2, but it was still happenning until I applied what @tazsid suggested

**Comment by vamsidhar-quagnitia** [comment]
Tried all ways mentioned but still getting same error or else difference errors but problem not solved after upgrading to flutter 2.8 this errors are happening

**Comment by christocracy** [comment]
@vamsidhar-quagnitia its *crucial* that you specify which version of the plugin you’re using.

**Comment by mzrcs** [comment]
hello @christocracy I am facing same issue. it was came earlier but it fixed itself with in a day. Now its been 4 days. I have noticed that  when application runs fine it https://google.bintray.com/ gives me 402 but when its error comes it https://google.bintray.com/  gives 502. following is my pub.yml
```
name: nexmove
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  cloud_firestore: ^2.4.0
  intl: ^0.15.8  
  location: ^4.3.0
  google_maps_flutter: ^0.5.19+2
  shared_preferences: ^0.5.3+4
  http: ^0.13.3
  url_launcher: ^5.1.1
  flutter_signature_pad: ^3.0.0
  image_picker: ^0.6.1+3
  permission_handler: ^8.0.0+2
  flutter_rating_bar: ^2.0.0+2
  flutter_barcode_scanner: ^2.0.0
  flutter_text_anchor: ^0.0.1
  #https://pub.dev/packages/flutter_geofencing#-readme-tab-
  # When using android use:
  #flutter_geofencing: ^0.1.2
  #https://pub.dev/packages/geofencing#-installing-tab-
  # When using iOS use:
  #geofencing: ^0.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  firebase_analytics_web: ^0.3.0+1
  firebase: ^9.0.1
  geofence_service: ^3.2.1
  firebase_messaging: ^11.2.3
  flutter_local_notifications: ^6.0.0
  #workmanager: ^0.4.1
  background_location: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**Comment by christocracy** [comment]
@mzrcs `background_fetch` does not exist in your posted `pubspec.yaml`.

**Comment by elmermj** [comment]
> There changes in `android/build.gradle` seen to work for me.
> 
> ```diff
>  buildscript {
>      ext.kotlin_version = '1.4.0' // Must use 1.3.0 or higher.
>      ext {
>          compileSdkVersion   = 30                // or higher
>          targetSdkVersion    = 30                // or higher
>          appCompatVersion    = "1.2.0"           // or higher
>     }
>  
>      repositories {
>          google()
> -        jcenter()
> +        mavenCentral()
>      }
>  
>      dependencies {
> -        classpath 'com.android.tools.build:gradle:4.0.1'
> +        classpath 'com.android.tools.build:gradle:4.2.2'
>          classpath 'com.google.gms:google-services:4.3.2'
>          classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.1'
>      }
>  }
>  
>  allprojects {
>      repositories {
>          google()
> -        jcenter()
>          maven {
>              // [required] background_fetch
>              url "${project(':background_fetch').projectDir}/libs"
>          }
> +        mavenCentral {
> +            content {
> +                excludeGroupByRegex "com\\.google\\.android\\.gms"
> +            }
> +        }
>  
>      }
>  }
> ```

Didn't work for me.
Error :
```
startup failed:
  build file 'C:\Work or Project\OneSmile\one-smile\android\build.gradle': 24: expecting '}', found 'com\.google\.android\.gms' @ line 24, column 38.
     +                excludeGroupByRegex "com\\.google\\.android\\.gms"
                                                             ^

  1 error
```
can you specify what does `excludeGroupByRegex "com\\.google\\.android\\.gms"` mean?????

**Comment by christocracy** [comment]
@elmermj are you even using the `background_fetch` plugin, which is the host of this repo?

**Comment by CDPIndia01** [comment]
Hello @christocracy ,

Currently facing the same issue since last 2 days. The application was working till last week.

To try and resolve the issue, tried debugging with the following steps -- 

1.  Increased the compileSdkVersion and targetSdkVersion from 29 to 30.
2. Removed **jcenter()**
3. Added **mavenCentral()**
4. Updated the **flutter_background_geolocation** from **^4.0.2** to **^4.3.2**

You may find the screenshot of the issue, build.gradle and pubspec.yaml for your reference

![Screenshot 2021-12-14 at 2 52 26 PM](https://user-images.githubusercontent.com/55577232/145970742-6785836b-34d5-43c6-82fb-2fef44b7907d.png)

Can you please help me with this? Adding the required code snippets below - 

**build.gradle**

```
buildscript {
    ext.kotlin_version = '1.3.50'
    ext {
        compileSdkVersion   = 30                // or higher
        targetSdkVersion    = 30                // or higher
        appCompatVersion    = "1.2.0"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
    }
}

allprojects {
    repositories {
        google()
        maven {
            // [required] flutter_background_geolocation
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            url "${project(':background_fetch').projectDir}/libs"
        }
        mavenCentral {
            content {
                excludeGroupByRegex "com\\.google\\.android\\.gms"
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**pubspec.yaml**
```
name: employeetracker
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.1+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  sqflite: ^1.3.2+3
  moor_flutter: ^3.1.0
  get: ^3.24.0
  intl: ^0.16.1
  shared_preferences: ^0.5.12+4
  lottie: any
  uuid: ^2.2.2
  google_maps_flutter: ^1.1.1
  geolocator: ^5.3.0
  geocoder: ^0.2.1
  path: ^1.7.0
  path_provider: ^1.6.27
  image_picker: any
  package_info: ^2.0.2
  modal_progress_hud: ^0.1.3
  trust_location: ^2.0.13
  adaptive_dialog: ^1.0.1
  permission_handler: ^5.0.1+1
  dio: ^4.0.0
  safe_device: ^1.0.6
  location: any
  firebase_messaging: any
  firebase_core: any
  webview_flutter: ^2.0.10
  flutter_local_notifications: any
  overlay_support: ^1.2.1
  flutter_tags: ^0.4.9+1
  flutter_background_geolocation: ^4.3.2
  platform_device_id: any
  flutter_inappwebview: ^5.3.2
  flutter_downloader: ^1.6.1
  device_info: ^2.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.4.1
  build_runner: ^1.11.1
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_new.jpg"
  adaptive_icon_foreground: "assets/images/app_icon_new.jpg"

  assets:
    - assets/images/empty.png
    - assets/images/ic_card_background.jpg
    - assets/images/ic_apply_leaves.png
    - assets/images/ic_job_reporting.png
    - assets/images/ic_my_attendance.png
    - assets/images/ic_task_management.png
    - assets/images/ic_view_records.png
    - assets/animation/location-search.json
    - assets/images/ic_image.png
    - assets/images/ic_pdf.png
    - assets/images/ic_about_image.jpg
    - assets/images/ic_logo_image.png
    - assets/images/ic_user_image.jpg
    - assets/images/ic_camera.jpg
    - assets/images/ic_notification.png
    - assets/images/ic_leave.png
    - assets/images/ic_notices.png
    - assets/images/explore_image.png
    - assets/images/ic_about.png
    - assets/images/ic_blog.png
    - assets/images/ic_contact_us.png
    - assets/images/ic_background_image.png
    - assets/images/ic_check.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
```

**Comment by ShadyZekry** [comment]
I was facing a similar problem until I changed the gradle distribution version in `android\gradle\wrapper\gradle-wrapper.properties`

```diff
- distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
+ distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
```
I hope this would help.

**Comment by mi318s** [comment]
I have the same issue 
"Could not GET 'https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'. Received status code 502 from server: Bad Gateway"

I tried to create project from the scratch and it worked successfully, so from there I added one by one all my plugins that I used in my original project, until image_picker is added. And the same error came up.

So, in my case plugin image_picker that caused it (don't know why). Hope it helps

**Comment by CDPIndia01** [comment]
> I have the same issue "Could not GET 'https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'. Received status code 502 from server: Bad Gateway"
> 
> I tried to create project from the scratch and it worked successfully, so from there I added one by one all my plugins that I used in my original project, until image_picker is added. And the same error came up.
> 
> So, in my case plugin image_picker that caused it (don't know why). Hope it helps

Thank you for the solution @mi318s .

which alternative library did you use for image_picker?

**Comment by AfriwanAhda** [comment]
I have solved this issue by downgrading the dependency on the `pubspec.yaml` file:
`background_fetch: ^0.6.0`
change to:
`background_fetch: ^0.5.0`
the app built and installed successfully.

**Comment by christocracy** [comment]
@AfriwanAhda downgrading to 0.5.0 is not a “solution” and there is no “problem” with 0.6.0.  You will have problems again once you upgrade your tools.gradle to 4.0 (as you should be doing).

read the [CHANGELOG](https://github.com/transistorsoft/flutter_background_fetch/blob/master/CHANGELOG.md#060---2020-06-11).

**Comment by christocracy** [comment]
Problems people are having in this thread are not due to the plugin.  It’s a combination of Gradle tools version and the deprecation of jcenter. 

Do **not** downgrade to 0.5.0.  You will be sorry once you upgrade your tools.gradle to 4+.

I have this plugin released for 3 other frameworks with the *exact same* Setup instructions (Cordova, Capacitor and React Native).  Only Flutter developers are having this issue.

**Comment by N1ght-Fury** [comment]
> I was facing a similar problem until I changed the gradle distribution version in `android\gradle\wrapper\gradle-wrapper.properties`
> 
> ```diff
> - distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
> + distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
> ```
> 
> I hope this would help.

I had the same issue today and this solved it. Thank you so much! Here is how my current build.gradle looks:

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral {
            content {
                excludeGroupByRegex "com\\.google\\.android\\.gms"
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by yy1300326388** [comment]
-  `android/build.gradle`
edited `classpath 'com.android.tools.build:gradle:3.6.3'`
to `classpath 'com.android.tools.build:gradle:4.2.0'`

- `android/gradle/wrapper/gradle-wrapper.properties`
edited `distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`
to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip`

**Comment by AshiqAS-dev** [comment]
@mi318s  Can you post your app-level and project-level build.gradle files? I want to check something. Maybe I can help you without changing the image_picker package that you are currently using. I mean I could give a try

**Comment by DiepEsc** [comment]
> Create for me a freshly generated flutter app which reproduces this then share that repo with me.

hi @christocracy 

Please take a look on flutter app
https://github.com/vinhhoangdo/background_fetch_reproduce

Thanks

**Comment by christocracy** [comment]
@DiepEsc you didn’t follow the [Required Android Setup Step](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md) linked in the readme.  There is more to installing this plugin than simply adding it to your pubspec.yaml.  The Setup is far more *complex* than most plugins.

please carefully read the readme.

**Comment by DiepEsc** [comment]
> 

Sorry, I will check it.

**Comment by nemoryoliver** [comment]
In my case, I was using `mopub_flutter` package... removing it solved my issue

**Comment by Srikanthjava972** [comment]
@christocracy @yy1300326388 @nemoryoliver @mi318s @poqueque I'm seeing below error since today, untill yesterday, I was able to run nativescript android app successfully.
![Uploading Screen Shot 2022-01-12 at 12.53.13 PM.png…]()

**Comment by cormalenv** [comment]
@mi318s @CDPIndia01 

Tested on a new project:

- added `background_fetch: ^1.0.3` - OK. 
- Added `image_picker: ^0.8.4+5` - OK. 
- Downgraded to `image_picker: 0.7.4` - FAILURE with XML issue. 

Solution for image_picker seems to be simply upgrade to latest. 

None of this helps in determining why the issue is occurring only with `background_fetch`. If I get time I'll try to isolate the `image_picker` version where this first appears and look at the changes at that level.

Not sure if this extends to other plugins but thanks @mi318s for isolating as much.

**Comment by codemaker2015** [comment]
You can resolve this issue by the following steps,

- **Change the `build.gradle` file as below**,
- 
- Change the kotlin version to 1.4.0 or higher
- 
- Remove` jcenter()` from repositories and add `mavenCentral() `
- 
- Change build gradle tools version to 4.1.0 or higher

```
 buildscript {
    ext.kotlin_version = '1.4.0' // or higher
    repositories {
        google()
        mavenCentral()  // add this
        maven {
            url 'https://maven.google.com'
        }
        // jcenter()  //remove or comment this
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'  // or higher
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()  // add this
        maven {
            url 'https://maven.google.com'
        }
        // jcenter()  // remove or comment this
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

- **Change the gradle distribution version on `gradle-wrapper.properties` file to 6.7 or higher**

```
#Fri Mar 23 08:50:38 IST 2022
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
```

- Upgrade the dependencies by the following command

```
flutter upgrade
```

- Done.

**Comment by Original-Tasty** [comment]
Doens't fix it

**Comment by vishwajit76** [comment]
same issue

**Comment by XterraEngine-dev** [comment]
Add the maven repository, this solved my problem

```jsx
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}
```

Flutter version:

```jsx
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (3 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

**Comment by christocracy** [comment]
`jcenter` [is deprecated](https://blog.gradle.org/jcenter-shutdown).  Delete it.
